version: 2.1
orbs:
  node: circleci/node@5.1.0

executors:
  my-exe:
    docker:
      - image: cimg/node:19.8.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
jobs:
  test:
    executor: my-exe
    steps:
      - checkout
      - run: npm rebuild
      - run: npm run test

workflows:
  my-workflow:
    jobs:
      - test
